# Generated by Django 4.2.16 on 2025-09-23 01:47

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la comunidad')),
                ('community_type', models.CharField(choices=[('department', 'Departamento'), ('condominium', 'Condominio')], max_length=20, verbose_name='Tipo de comunidad')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('community_code', models.CharField(max_length=50, unique=True, verbose_name='Código de comunidad')),
                ('admin_contact', models.EmailField(max_length=254, verbose_name='Contacto del administrador')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Comunidad',
                'verbose_name_plural': 'Comunidades',
            },
        ),
        migrations.CreateModel(
            name='CommunityEmailRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('tower', models.CharField(blank=True, max_length=100, null=True, verbose_name='Torre/Edificio')),
                ('house_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de vivienda')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('is_used', models.BooleanField(default=False, verbose_name='Usado')),
                ('loaded_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('loaded_by', models.EmailField(max_length=254, verbose_name='Cargado por')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community', verbose_name='Comunidad')),
            ],
            options={
                'verbose_name': 'Registro de correo',
                'verbose_name_plural': 'Registro de correos',
                'unique_together': {('community', 'email')},
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('tower', models.CharField(blank=True, max_length=100, null=True, verbose_name='Torre/Edificio')),
                ('house_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de vivienda')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('role', models.CharField(choices=[('resident', 'Residente'), ('admin', 'Administrador'), ('superadmin', 'Super Administrador')], default='resident', max_length=20, verbose_name='Rol')),
                ('is_active_user', models.BooleanField(default=True, verbose_name='Usuario activo')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community', verbose_name='Comunidad')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'unique_together': {('community', 'email')},
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
