# Generated by Django 4.2.16 on 2025-09-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_customuser_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityemailregistry',
            name='loaded_by',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Cargado por'),
        ),
    ]
